url: "https://seniorneurocare.com"
baseurl: ""

# Site Settings
title: Dr. Andrea Ortiz OrdoÃ±ez
email: contact@seniorneurocare.com
description: >-
  Geriatric and Spine Neurosurgery Specialist focused on complex adult and senior spine interventions. Transitioning to U.S. clinical practice.
twitter_username: 
github_username: himy2u

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

enforce_ssl: true

collections:
  achievements:
    output: true
    permalink: /achievements/:slug/

defaults:
  -
    scope:
      path: ""
      type: "achievements"
    values:
      lang: "en"
